# Gradle \uB370\uBAAC(\uBC31\uADF8\uB77C\uC6B4\uB4DC \uD504\uB85C\uC138\uC2A4)\uC744 \uD56D\uC0C1 \uCF1C\uB46C\uC11C \uC2DC\uC791 \uC18D\uB3C4\uB97C \uB192\uC784
org.gradle.daemon=true

# \uBCD1\uB82C \uC791\uC5C5 \uC218\uD589 (\uCF54\uC5B4\uAC00 \uC5EC\uB7EC \uAC1C\uBA74 \uBE68\uB77C\uC9D0)
org.gradle.parallel=true

# \uBE4C\uB4DC \uCE90\uC2DC \uC0AC\uC6A9 (\uC774\uC804\uC5D0 \uD588\uB358 \uC791\uC5C5\uC744 \uC7AC\uC0AC\uC6A9)
org.gradle.caching=true

# JVM \uBA54\uBAA8\uB9AC \uD655\uBCF4 (\uD544\uC694\uC2DC \uB298\uB9BC)
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
mysqlConnectorVersion=9.4.0
flatLafVersion=3.6.2
bcryptVersion=0.4
junitBomVersion=5.10.0