# Root configuration file for SonarCloud

# 1. Set your project key (from your SonarCloud project)
sonar.projectKey=mingjae1_SignupApplication

sonar.organization=mingjae1

# 2. Tell SonarCloud where your source (.java) files are
sonar.sources=src

# 3. Tell SonarCloud where your compiled (.class) files will be
# (We will create this 'bin' folder in the next step)
sonar.java.binaries=bin

# 4. Tell SonarCloud where your external libraries (.jar) are
# !! IMPORTANT: Change the .jar file name to match yours exactly !!
sonar.java.libraries=lib/mysql-connector-j-9.4.0.jar